input ChangePasswordInput {
  currentPassword: String!
  newPassword: String!
}

input CreatePostInput {
  text: String!
}

scalar DateTime

input DeletePostInput {
  id: ID!
}

input EditPostInput {
  id: ID!
  text: String!
}

input EditUserInput {
  username: String
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  changePassword(input: ChangePasswordInput!): Result!
  createPost(input: CreatePostInput!): Post!
  deletePost(input: DeletePostInput!): Post!
  editPost(input: EditPostInput!): Post!
  editUser(input: EditUserInput!): User!
  login(input: LoginInput!): User!
  logout: Result!
  signUp(input: SignUpInput!): User!
}

type Post {
  createdAt: DateTime!
  id: ID!
  text: String!
  updatedAt: DateTime!
  user: User
}

type Query {
  me: User
  post(id: ID!): Post!
  posts: [Post!]!
  users: [User!]!
}

enum Result {
  SUCCESS
}

input SignUpInput {
  email: String!
  password: String!
  username: String!
}

type User {
  id: ID!
  username: String!
}
